# Generated by Django 5.0.6 on 2024-06-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_story_response_alter_story_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='recipient',
        ),
        migrations.AddField(
            model_name='story',
            name='partner_story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
